import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication, ValidationPipe } from '@nestjs/common';
import request from 'supertest';
import { AppModule } from './../src/app.module';
import { PrismaService } from '../src/prisma/prisma.service';

describe('Auth Security Re-Audit (e2e)', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let testUser: any;
  let testTenant: any;
  let accessToken: string;
  let refreshToken: string;
  let sessionId: string;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    app.useGlobalPipes(new ValidationPipe({ transform: true }));
    await app.init();

    prisma = app.get(PrismaService);
    
    // Clean up
    await prisma.authSession.deleteMany({});
    await prisma.authAuditLog.deleteMany({});
    await prisma.user.deleteMany({});
    await prisma.tenant.deleteMany({});

    // Setup Test Data
    testTenant = await prisma.tenant.create({
      data: { name: 'Audit Tenant', ruc: '0999999999001' }
    });

    const res = await request(app.getHttpServer())
      .post('/auth/register')
      .send({
        email: 'audit@test.com',
        password: 'Password123!',
        name: 'Audit User',
        tenantId: testTenant.id
      });
    
    testUser = await prisma.user.findUnique({ where: { email: 'audit@test.com' } });

    // Ensure user exists
    expect(testUser).toBeDefined();

    const loginRes = await request(app.getHttpServer())
      .post('/auth/login')
      .send({
        email: 'audit@test.com',
        password: 'Password123!'
      });

    accessToken = loginRes.body.accessToken;
    refreshToken = loginRes.body.refreshToken;
    expect(accessToken).toBeDefined();
    
    const session = await prisma.authSession.findFirst({ where: { userId: testUser.id } });
    sessionId = session.id;
  });

  afterAll(async () => {
    await prisma.authSession.deleteMany({});
    await prisma.authAuditLog.deleteMany({});
    await prisma.user.deleteMany({});
    await prisma.tenant.deleteMany({});
    await app.close();
  });

  it('Phase 1: Concurrent Refresh Race Condition (Should fail if race exists)', async () => {
    // Attempt 3 concurrent refresh requests with the same token
    const results = await Promise.all([
      request(app.getHttpServer()).post('/auth/refresh').send({ refreshToken }),
      request(app.getHttpServer()).post('/auth/refresh').send({ refreshToken }),
      request(app.getHttpServer()).post('/auth/refresh').send({ refreshToken })
    ]);

    const successes = results.filter(r => r.status === 201 || r.status === 200);
    const failures = results.filter(r => r.status === 401);

    // ONLY one should succeed because of the row lock
    expect(successes.length).toBe(1);
    expect(failures.length).toBe(2);

    // Update tokens for next tests
    accessToken = successes[0].body.accessToken;
    refreshToken = successes[0].body.refreshToken;
  });

  it('Phase 1b: Replay Attack Revokes Family', async () => {
    // Because of the concurrent race in Phase 1 being treated as a retry, the family should NOT have been revoked!
    // Let's verify that the new token generated by the single successful request is VALID.
    const newRefreshRes = await request(app.getHttpServer())
      .post('/auth/refresh')
      .send({ refreshToken }); // The one from successes[0]

    expect(newRefreshRes.status).toBe(200); // Or 200 depending on your controller

    const newRefreshToken = newRefreshRes.body.refreshToken;

    // Now, attempt a replay attack using the OLD (revoked) refresh token (which is definitely older than 15s, or we can mock time, but for the sake of the test, let's sleep for 16s... actually, sleeping for 16s in a test is bad. Let's manually backdate the revokedAt in the DB)
    
    // First, let's manually backdate the `revokedAt` of the previous token to simulate it being an old revocation
    await prisma.authSession.updateMany({
      where: { refreshToken },
      data: { revokedAt: new Date(Date.now() - 20000) }
    });

    const replayRes = await request(app.getHttpServer())
      .post('/auth/refresh')
      .send({ refreshToken }); // Old token, backdated
    
    expect(replayRes.status).toBe(401);
    expect(replayRes.body.message).toContain('suspicious activity');

    // Verify the entire family is revoked, meaning the new token should ALSO fail
    const replayNewRes = await request(app.getHttpServer())
      .post('/auth/refresh')
      .send({ refreshToken: newRefreshToken });
    
    expect(replayNewRes.status).toBe(401); // Family should be revoked!

    // Login again for Phase 4
    const loginRes2 = await request(app.getHttpServer())
      .post('/auth/login')
      .send({
        email: 'audit@test.com',
        password: 'Password123!'
      });
    accessToken = loginRes2.body.accessToken;
    refreshToken = loginRes2.body.refreshToken;
  });

  it('Phase 4: Logout resilience', async () => {
    // Logout should successfully invalidate the session in DB
    const logoutRes = await request(app.getHttpServer())
      .post('/auth/logout')
      .set('Authorization', `Bearer ${accessToken}`)
      .send({ refreshToken });
    
    expect(logoutRes.status).toBe(200);

    // Ensure session is revoked in DB
    const session = await prisma.authSession.findFirst({ where: { refreshToken } });
    expect(session.revokedAt).not.toBeNull();
  });
});
